import { Injectable } from '@angular/core';
import { Pokemon } from './pokemon';

@Injectable({ providedIn: 'root' })
export class PokemonMapperService {

  private typeMap: Record<string, string> = {
    fire: 'Fuego',
    water: 'Agua',
    grass: 'Planta',
    electric: 'Eléctrico',
    bug: 'Bicho',
    normal: 'Normal',
    flying: 'Volador',
    poison: 'Veneno',
    dragon: 'Dragón',
    psychic: 'Psíquico',
    dark: 'Siniestro',
    ghost: 'Fantasma',
    fighting: 'Lucha',
    fairy: 'Hada',
    rock: 'Roca',
    steel: 'Acero',
    ground: 'Tierra',
    ice: 'Hielo'
  };

  private abilityMap: Record<string, string> = {
    overgrow: 'Espesura',
    blaze: 'Mar de Llamas',
    torrent: 'Torrente',
    'shield-dust': 'Polvo Escudo',
    'shed-skin': 'Mudar',
    'compound-eyes': 'Ojo Compuesto',
    swarm: 'Enjambre',
    'keen-eye': 'Vista Lince',
    'run-away': 'Fuga',
    intimidate: 'Intimidación',
    static: 'Electricidad Estática',
    'sand-veil': 'Velo Arena',
    'poison-point': 'Punto Tóxico',
    'cute-charm': 'Encanto',
    'flash-fire': 'Absorbe Fuego',
    'inner-focus': 'Fuerza Mental',
    chlorophyll: 'Clorofila',
    'effect-spore': 'Efecto Espora',
    'solar-power': 'Poder Solar',
    'rain-dish': 'Cura Lluvia',
    'tinted-lens': 'Cromolente',
    sniper: 'Francotirador',
    'tangled-feet': 'Tumbos',
    guts: 'Agallas',
    'lightning-rod': 'Pararrayos',
    'sand-rush': 'Ímpetu Arena',
    rivalry: 'Rivalidad',
    'magic-guard': 'Muro Mágico',
    drought: 'Sequía',
    competitive: 'Tenacidad',
    infiltrator: 'Allanamiento',
    stench: 'Hedor',
    'dry-skin': 'Piel Seca',
    'arena-trap': 'Trampa Arena',
    'big-pecks': 'Sacapecho',
    hustle: 'Entusiasmo',
    unnerve: 'Nerviosismo',
    'sheer-force': 'Potencia Bruta',
    'friend-guard': 'Compiescolta',
    unaware: 'Ignorante',
    frisk: 'Cacheo',
    damp: 'Humedad',
    'wonder-skin': 'Piel Milagro',
    'sand-force': 'Poder Arena',
    pickup: 'Recogida',
    technician: 'Experto',
    limber: 'Flexibilidad',
    'cloud-nine': 'Aclimatación',
    'swift-swim': 'Nado Rápido',
    'vital-spirit': 'Espíritu Vital',
    'anger-point': 'Irascible',
    defiant: 'Competitivo',
    justified: 'Justiciero',
    'water-absorb': 'Absorbe Agua',
    synchronize: 'Sincronía',
    'no-guard': 'Indefenso',
    'steadfast': 'Impasible',
    gluttony: 'Gula',
    'clear-body': 'Cuerpo Puro',
    'liquid-ooze': 'Viscosecreción',
    'rock-head': 'Cabeza Roca',
    sturdy: 'Robustez',
    'flame-body': 'Cuerpo Llama',
    oblivious: 'Despiste',
    'own-tempo': 'Ritmo Propio',
    regenerator: 'Regeneración',
    'magnet-pull': 'Imán',
    analytic: 'Cálculo Final',
    'early-bird': 'Madrugar',
    'thick-fat': 'Sebo',
    hydration: 'Hidratación',
    'ice-body': 'Gélido',
    'sticky-hold': 'Viscosidad',
    'poison-touch': 'Toque Tóxico',
    'shell-armor': 'Caparazón',
    'skill-link': 'Encadenado',
    overcoat: 'Funda',
    levitate: 'Levitación',
    'cursed-body': 'Cuerpo Maldito',
    'weak-armor': 'Armadura Frágil',
    insomnia: 'Insomnio',
    forewarn: 'Alerta',
    'hyper-cutter': 'Corte Fuerte',
    soundproof: 'Insonorizar',
    aftermath: 'Detonación',
    harvest: 'Cosecha',
    'battle-armor': 'Armadura Batalla',
    reckless: 'Audaz',
    unburden: 'Liviano',
    'iron-fist': 'Puño Férreo',
    'neutralizing-gas': 'Gas Reactivo',
    'natural-cure': 'Cura Natural',
    'serene-grace': 'Dicha',
    healer: 'Alma Cura',
    'leaf-guard': 'Defensa Hoja',
    scrappy: 'Intrépido',
    'water-veil': 'Velo Agua',
    illuminate: 'Iluminación',
    filter: 'Filtro',
    'mold-breaker': 'Rompemoldes',
    moxie: 'Autoestima',
    rattled: 'Cobardía',
    imposter: 'Impostor',
    adaptability: 'Adaptable',
    anticipation: 'Anticipación',
    'volt-absorb': 'Absorbe Electricidad',
    'quick-feet': 'Pies Rápidos',
    trace: 'Calco',
    download: 'Descarga',
    pressure: 'Presión',
    immunity: 'Inmunidad',
    'snow-cloak': 'Manto Níveo',
    'marvel-scale': 'Escama Especial',
    multiscale: 'Multiescamas',
    'super-luck': 'Afortunado',
    'magic-bounce': 'Espejo Mágico',
    plus: 'Más',
    'huge-power': 'Potencia',
    'sap-sipper': 'Herbívoro',
    drizzle: 'Llovizna',
    'speed-boost': 'Impulso',
    prankster: 'Bromista',
    'shadow-tag': 'Sombra Trampa',
    telepathy: 'Telepatía',
    'light-metal': 'Metal Liviano',
    contrary: 'Respondón',
    pickpocket: 'Hurto',
    'honey-gather': 'Recogemiel',
    'magma-armor': 'Escudo Magma',
    moody: 'Veleta',
    'suction-cups': 'Ventosas',
    'sand-stream': 'Chorro Arena',
    'wind-rider': 'Surcavientos',
    'poison-heal': 'Antídoto',
    truant: 'Pereza',
    'wonder-guard': 'Superguarda',
    normalize: 'Normalidad',
    stall: 'Rezagado',
    'heavy-metal': 'Metal Pesado',
    'pure-power': 'Energía Pura',
    minus: 'Menos',
    'rough-skin': 'Piel Tosca',
    simple: 'Simple',
    'solid-rock': 'Roca Sólida',
    'toxic-boost': 'Ímpetu tóxico',
    'storm-drain': 'Colector',
    forecast: 'Predicción',
    'color-change': 'Cambio Color',
    protean: 'Mutatipo',
    'air-lock': 'Esclusa de Aire',
    'flower-gift': 'Don Floral',
    klutz: 'Zoquete',
    heatproof: 'Ignífugo',
    'snow-warning': 'Nevada',
    'motor-drive': 'Electromotor',
    sharpness: 'Cortante',
    'slow-start': 'Inicio Lento',
    'bad-dreams': 'Mal Sueño',
    multitype: 'Multitipo',
    'victory-star': 'Tinovictoria',
    'zen-mode': 'Modo Daruma',
    mummy: 'Momia',
    defeatist: 'Flaqueza',
    illusion: 'Ilusión',
    'iron-barbs': 'Punta Acero',
    'slush-rush': 'Quitanieves',
    'white-smoke': 'Humo Blanco',
    turboblaze: 'Turbollama',
    teravolt: 'Teravoltaje',
    bulletproof: 'Antibalas',
    magician: 'Prestidigitador',
    'cheek-pouch': 'Carrillo',
    'gale-wings': 'Alas Vendaval',
    'flower-veil': 'Velo Flor',
    symbiosis: 'Simbiosis',
    'grass-pelt': 'Manto Frondoso',
    'fur-coat': 'Pelaje Recio',
    'stance-change': 'Cambio Táctico',
    'aroma-veil': 'Velo Aroma',
    'sweet-veil': 'Velo Dulce',
    'tough-claws': 'Garra Dura',
    'mega-launcher': 'Megadisparador',
    'strong-jaw': 'Mandíbula Fuerte',
    refrigerate: 'Piel Helada',
    pixilate: 'Piel Feérica',
    gooey: 'Baba',
    'fairy-aura': 'Aura Feérica',
    'dark-aura': 'Aura Oscura',
    'aura-break': 'Rompeaura',
    'long-reach': 'Remoto',
    'liquid-voice': 'Voz Fluida',
    stakeout: 'Vigilante',
    battery: 'Batería',
    dancer: 'Pareja de Baile',
    schooling: 'Banco',
    merciless: 'Ensañamiento',
    stamina: 'Firmeza',
    'water-bubble': 'Pompa',
    corrosion: 'Corrosión',
    fluffy: 'Peluche',
    'queenly-majesty': 'Regia Presencia',
    triage: 'Primer Auxilio',
    receiver: 'Receptor',
    'wimp-out': 'Huida',
    'emergency-exit': 'Retirada',
    'water-compaction': 'Hidrorrefuerzo',
    'innards-out': 'Revés',
    'rks-system': 'Sistema Alfa',
    'shields-down': 'Escudo Limitado',
    comatose: 'Letargo Perenne',
    disguise: 'Disfraz',
    dazzling: 'Cuerpo Vivido',
    berserk: 'Cólera',
    steelworker: 'Acero Templado',
    'electric-surge': 'Electrogénesis',
    'psychic-surge': 'Psicogénesis',
    'grassy-surge': 'Herbogénesis',
    'misty-surge': 'Nebulogénesis',
    'full-metal-body': 'Guardia Metálica',
    'shadow-shield': 'Guardia Espectro',
    'beast-boost': 'Ultraimpulso',
    'prism-armor': 'Armadura Prisma',
    'soul-heart': 'Coránima',
    libero: 'Líbero',
    'mirror-armor': 'Coraza Reflejo',
    'cotton-down': 'Pelusa',
    'ball-fetch': 'Recogebolas',
    'steam-engine': 'Combustible',
    ripen: 'Maduración',
    'sand-spit': 'Expulsarena',
    'gulp-missile': 'Tragamisil',
    'propeller-tail': 'Hélice Caudal',
    'punk-rock': 'Punk Rock',
    'steely-spirit': 'Alma Acerada',
    'perish-body': 'Cuerpo Mortal',
    'screen-cleaner': 'Antibarrera',
    'wandering-spirit': 'Alma Errante',
    'ice-scales': 'Escama de Hielo',
    'power-spot': 'Fuente Energía',
    'ice-face': 'Cara de Hielo',
    'hunger-switch': 'Mutapetito',
    stalwart: 'Acérrimo',
    'intrepid-sword': 'Espada Indómita',
    'dauntless-shield': 'Escudo Recio',
    'unseen-fist': 'Puño Invisible',
    transistor: 'Transistor',
    'dragons-maw': 'Mandíbula Dragón',
    'chilling-neigh': 'Relincho Blanco',
    'grim-neigh': 'Relincho Negro',
    'lingering-aroma': 'Olor Persistente',
    'well-baked-body': 'Cuerpo Horneado',
    'seed-sower': 'Disemillar',
    'purifying-salt': 'Sal Purificadora',
    electromorphosis: 'Dínamo',
    'wind-power': 'Energía Eólica',
    'guard-dog': 'Perro Guardían',
    'mycelium-might': 'Poder Fúngico',
    'anger-shell': 'Coraza Ira',
    opportunist: 'Oportunista',
    'rocky-payload': 'Transportarrocas',
    'zero-to-hero': 'Cambio Heróico',
    'earth-eater': 'Geofagia',
    'toxic-debris': 'Capa Tóxica',
    costar: 'Unísono',
    commander: 'Comandar',
    'cud-chew': 'Rumia',
    'armor-tail': 'Cola Armadura',
    'supreme-overlord': 'General Supremo',
    protosynthesis: 'Paleosíntesis',
    'quark-drive': 'Carga Cuark',
    'thermal-exchange': 'Termoconversión',
    'good-as-gold': 'Cuerpo Áureo',
    'tablets-of-ruin': 'Tablero Debacle',
    'sword-of-ruin': 'Espada Debacle',
    'vessel-of-ruin': 'Caldero Debacle',
    'beads-of-ruin': 'Abalorio Debacle',
    'orichalcum-pulse': 'Latido Oricalco',
    'hadron-engine': 'Motor Hadrónico',
    'supersweet-syrup': 'Néctar Dulce',
    hospitality: 'Hospitalidad',
    'toxic-chain': 'Cadena Tóxica',
    'tera-shift': 'Teracambio',
    'poison-puppeteer': 'Títere Tóxico',
    'parental-bond': 'Amor Filial',
    aerilate: 'Piel Celeste',
    'primordial-sea': 'Mar del Albor',
    'desolate-land': 'Tierra del Ocaso',
    'delta-stream': 'Ráfaga Delta',
    'surge-surfer': 'Cola Surf',
    'tangling-hair': 'Rizos Rebeldes',
    galvanize: 'Piel Eléctrica',
    'power-of-alchemy': 'Reacción Química',
    'battle-bond': 'Fuerte Afecto',
    'power-construct': 'Agrupamiento',
    neuroforce: 'Fuerza Cerebral',
    'pastel-veil': 'Velo Pastel',
    'quick-draw': 'Mano Rápida',
    'curious-medicine': 'Medicina Extraña',
    'gorilla-tactics': 'Monotema',
    mimicry: 'Mimetismo',
    'as-one-glastrier': 'Unidad Ecuestre',
    'as-one-spectrier': 'Unidad Ecuestre',
    'minds-eye': 'Ojo Mental',
    'tera-shell': 'Teracaparazón',
    'teraform-zero': 'Teraformación 0',
    'mega-sol': 'Megasolar',
    dragonize: 'Piel Dragontina',
    'piercing-drill': 'Turbotaladro',
    'spicy-spray': 'Salpicante',
  };

  private statMap: Record<string, string> = {
    hp: 'PS',
    attack: 'Ataque',
    defense: 'Defensa',
    'special-attack': 'Ataque Especial',
    'special-defense': 'Defensa Especial',
    speed: 'Velocidad'
  }

  mapPokemon(p: any): Pokemon {
    return {
      ...p,

      sprite: p.sprites?.other.home.front_default,

      // tipos traducidos
      types: p.types.map((t: any) => ({
        ...t,
        type: {
          name: this.typeMap[t.type.name] ?? t.type.name
        }
      })),

      // habilidades traducidas
      abilities: p.abilities.map((a: any) => ({
        ...a,
        ability: {
          name: this.abilityMap[a.ability.name] ?? a.ability.name
        }
      })),

      height: p.height,
      weight: p.weight,

      stats: p.stats.map((s: any) => ({
        ...s,
        stat: {
          name: this.statMap[s.stat.name] ?? s.stat.name
        }
      }))
    };
  }
}