import { Injectable } from '@angular/core';
import { Pokemon } from './pokemon';
import { PokemonDetailVM } from './pokemon';
import { AbilityVM } from '../pokemondetail/pokemondetail';

@Injectable({ providedIn: 'root' })
export class PokemonMapperService {

  public typeMap: Record<string, string> = {
    fire: 'Fuego',
    water: 'Agua',
    grass: 'Planta',
    electric: 'Eléctrico',
    bug: 'Bicho',
    normal: 'Normal',
    flying: 'Volador',
    poison: 'Veneno',
    dragon: 'Dragón',
    psychic: 'Psíquico',
    dark: 'Siniestro',
    ghost: 'Fantasma',
    fighting: 'Lucha',
    fairy: 'Hada',
    rock: 'Roca',
    steel: 'Acero',
    ground: 'Tierra',
    ice: 'Hielo'
  };

  public abilityMap: Record<string, string> = {
    overgrow: 'Espesura',
    blaze: 'Mar de Llamas',
    torrent: 'Torrente',
    'shield-dust': 'Polvo Escudo',
    'shed-skin': 'Mudar',
    'compound-eyes': 'Ojo Compuesto',
    swarm: 'Enjambre',
    'keen-eye': 'Vista Lince',
    'run-away': 'Fuga',
    intimidate: 'Intimidación',
    static: 'Electricidad Estática',
    'sand-veil': 'Velo Arena',
    'poison-point': 'Punto Tóxico',
    'cute-charm': 'Encanto',
    'flash-fire': 'Absorbe Fuego',
    'inner-focus': 'Fuerza Mental',
    chlorophyll: 'Clorofila',
    'effect-spore': 'Efecto Espora',
    'solar-power': 'Poder Solar',
    'rain-dish': 'Cura Lluvia',
    'tinted-lens': 'Cromolente',
    sniper: 'Francotirador',
    'tangled-feet': 'Tumbos',
    guts: 'Agallas',
    'lightning-rod': 'Pararrayos',
    'sand-rush': 'Ímpetu Arena',
    rivalry: 'Rivalidad',
    'magic-guard': 'Muro Mágico',
    drought: 'Sequía',
    competitive: 'Tenacidad',
    infiltrator: 'Allanamiento',
    stench: 'Hedor',
    'dry-skin': 'Piel Seca',
    'arena-trap': 'Trampa Arena',
    'big-pecks': 'Sacapecho',
    hustle: 'Entusiasmo',
    unnerve: 'Nerviosismo',
    'sheer-force': 'Potencia Bruta',
    'friend-guard': 'Compiescolta',
    unaware: 'Ignorante',
    frisk: 'Cacheo',
    damp: 'Humedad',
    'wonder-skin': 'Piel Milagro',
    'sand-force': 'Poder Arena',
    pickup: 'Recogida',
    technician: 'Experto',
    limber: 'Flexibilidad',
    'cloud-nine': 'Aclimatación',
    'swift-swim': 'Nado Rápido',
    'vital-spirit': 'Espíritu Vital',
    'anger-point': 'Irascible',
    defiant: 'Competitivo',
    justified: 'Justiciero',
    'water-absorb': 'Absorbe Agua',
    synchronize: 'Sincronía',
    'no-guard': 'Indefenso',
    'steadfast': 'Impasible',
    gluttony: 'Gula',
    'clear-body': 'Cuerpo Puro',
    'liquid-ooze': 'Viscosecreción',
    'rock-head': 'Cabeza Roca',
    sturdy: 'Robustez',
    'flame-body': 'Cuerpo Llama',
    oblivious: 'Despiste',
    'own-tempo': 'Ritmo Propio',
    regenerator: 'Regeneración',
    'magnet-pull': 'Imán',
    analytic: 'Cálculo Final',
    'early-bird': 'Madrugar',
    'thick-fat': 'Sebo',
    hydration: 'Hidratación',
    'ice-body': 'Gélido',
    'sticky-hold': 'Viscosidad',
    'poison-touch': 'Toque Tóxico',
    'shell-armor': 'Caparazón',
    'skill-link': 'Encadenado',
    overcoat: 'Funda',
    levitate: 'Levitación',
    'cursed-body': 'Cuerpo Maldito',
    'weak-armor': 'Armadura Frágil',
    insomnia: 'Insomnio',
    forewarn: 'Alerta',
    'hyper-cutter': 'Corte Fuerte',
    soundproof: 'Insonorizar',
    aftermath: 'Detonación',
    harvest: 'Cosecha',
    'battle-armor': 'Armadura Batalla',
    reckless: 'Audaz',
    unburden: 'Liviano',
    'iron-fist': 'Puño Férreo',
    'neutralizing-gas': 'Gas Reactivo',
    'natural-cure': 'Cura Natural',
    'serene-grace': 'Dicha',
    healer: 'Alma Cura',
    'leaf-guard': 'Defensa Hoja',
    scrappy: 'Intrépido',
    'water-veil': 'Velo Agua',
    illuminate: 'Iluminación',
    filter: 'Filtro',
    'mold-breaker': 'Rompemoldes',
    moxie: 'Autoestima',
    rattled: 'Cobardía',
    imposter: 'Impostor',
    adaptability: 'Adaptable',
    anticipation: 'Anticipación',
    'volt-absorb': 'Absorbe Electricidad',
    'quick-feet': 'Pies Rápidos',
    trace: 'Calco',
    download: 'Descarga',
    pressure: 'Presión',
    immunity: 'Inmunidad',
    'snow-cloak': 'Manto Níveo',
    'marvel-scale': 'Escama Especial',
    multiscale: 'Multiescamas',
    'super-luck': 'Afortunado',
    'magic-bounce': 'Espejo Mágico',
    plus: 'Más',
    'huge-power': 'Potencia',
    'sap-sipper': 'Herbívoro',
    drizzle: 'Llovizna',
    'speed-boost': 'Impulso',
    prankster: 'Bromista',
    'shadow-tag': 'Sombra Trampa',
    telepathy: 'Telepatía',
    'light-metal': 'Metal Liviano',
    contrary: 'Respondón',
    pickpocket: 'Hurto',
    'honey-gather': 'Recogemiel',
    'magma-armor': 'Escudo Magma',
    moody: 'Veleta',
    'suction-cups': 'Ventosas',
    'sand-stream': 'Chorro Arena',
    'wind-rider': 'Surcavientos',
    'poison-heal': 'Antídoto',
    truant: 'Pereza',
    'wonder-guard': 'Superguarda',
    normalize: 'Normalidad',
    stall: 'Rezagado',
    'heavy-metal': 'Metal Pesado',
    'pure-power': 'Energía Pura',
    minus: 'Menos',
    'rough-skin': 'Piel Tosca',
    simple: 'Simple',
    'solid-rock': 'Roca Sólida',
    'toxic-boost': 'Ímpetu tóxico',
    'storm-drain': 'Colector',
    forecast: 'Predicción',
    'color-change': 'Cambio Color',
    protean: 'Mutatipo',
    'air-lock': 'Esclusa de Aire',
    'flower-gift': 'Don Floral',
    klutz: 'Zoquete',
    heatproof: 'Ignífugo',
    'snow-warning': 'Nevada',
    'motor-drive': 'Electromotor',
    sharpness: 'Cortante',
    'slow-start': 'Inicio Lento',
    'bad-dreams': 'Mal Sueño',
    multitype: 'Multitipo',
    'victory-star': 'Tinovictoria',
    'zen-mode': 'Modo Daruma',
    mummy: 'Momia',
    defeatist: 'Flaqueza',
    illusion: 'Ilusión',
    'iron-barbs': 'Punta Acero',
    'slush-rush': 'Quitanieves',
    'white-smoke': 'Humo Blanco',
    turboblaze: 'Turbollama',
    teravolt: 'Teravoltaje',
    bulletproof: 'Antibalas',
    magician: 'Prestidigitador',
    'cheek-pouch': 'Carrillo',
    'gale-wings': 'Alas Vendaval',
    'flower-veil': 'Velo Flor',
    symbiosis: 'Simbiosis',
    'grass-pelt': 'Manto Frondoso',
    'fur-coat': 'Pelaje Recio',
    'stance-change': 'Cambio Táctico',
    'aroma-veil': 'Velo Aroma',
    'sweet-veil': 'Velo Dulce',
    'tough-claws': 'Garra Dura',
    'mega-launcher': 'Megadisparador',
    'strong-jaw': 'Mandíbula Fuerte',
    refrigerate: 'Piel Helada',
    pixilate: 'Piel Feérica',
    gooey: 'Baba',
    'fairy-aura': 'Aura Feérica',
    'dark-aura': 'Aura Oscura',
    'aura-break': 'Rompeaura',
    'long-reach': 'Remoto',
    'liquid-voice': 'Voz Fluida',
    stakeout: 'Vigilante',
    battery: 'Batería',
    dancer: 'Pareja de Baile',
    schooling: 'Banco',
    merciless: 'Ensañamiento',
    stamina: 'Firmeza',
    'water-bubble': 'Pompa',
    corrosion: 'Corrosión',
    fluffy: 'Peluche',
    'queenly-majesty': 'Regia Presencia',
    triage: 'Primer Auxilio',
    receiver: 'Receptor',
    'wimp-out': 'Huida',
    'emergency-exit': 'Retirada',
    'water-compaction': 'Hidrorrefuerzo',
    'innards-out': 'Revés',
    'rks-system': 'Sistema Alfa',
    'shields-down': 'Escudo Limitado',
    comatose: 'Letargo Perenne',
    disguise: 'Disfraz',
    dazzling: 'Cuerpo Vivido',
    berserk: 'Cólera',
    steelworker: 'Acero Templado',
    'electric-surge': 'Electrogénesis',
    'psychic-surge': 'Psicogénesis',
    'grassy-surge': 'Herbogénesis',
    'misty-surge': 'Nebulogénesis',
    'full-metal-body': 'Guardia Metálica',
    'shadow-shield': 'Guardia Espectro',
    'beast-boost': 'Ultraimpulso',
    'prism-armor': 'Armadura Prisma',
    'soul-heart': 'Coránima',
    libero: 'Líbero',
    'mirror-armor': 'Coraza Reflejo',
    'cotton-down': 'Pelusa',
    'ball-fetch': 'Recogebolas',
    'steam-engine': 'Combustible',
    ripen: 'Maduración',
    'sand-spit': 'Expulsarena',
    'gulp-missile': 'Tragamisil',
    'propeller-tail': 'Hélice Caudal',
    'punk-rock': 'Punk Rock',
    'steely-spirit': 'Alma Acerada',
    'perish-body': 'Cuerpo Mortal',
    'screen-cleaner': 'Antibarrera',
    'wandering-spirit': 'Alma Errante',
    'ice-scales': 'Escama de Hielo',
    'power-spot': 'Fuente Energía',
    'ice-face': 'Cara de Hielo',
    'hunger-switch': 'Mutapetito',
    stalwart: 'Acérrimo',
    'intrepid-sword': 'Espada Indómita',
    'dauntless-shield': 'Escudo Recio',
    'unseen-fist': 'Puño Invisible',
    transistor: 'Transistor',
    'dragons-maw': 'Mandíbula Dragón',
    'chilling-neigh': 'Relincho Blanco',
    'grim-neigh': 'Relincho Negro',
    'lingering-aroma': 'Olor Persistente',
    'well-baked-body': 'Cuerpo Horneado',
    'seed-sower': 'Disemillar',
    'purifying-salt': 'Sal Purificadora',
    electromorphosis: 'Dínamo',
    'wind-power': 'Energía Eólica',
    'guard-dog': 'Perro Guardían',
    'mycelium-might': 'Poder Fúngico',
    'anger-shell': 'Coraza Ira',
    opportunist: 'Oportunista',
    'rocky-payload': 'Transportarrocas',
    'zero-to-hero': 'Cambio Heróico',
    'earth-eater': 'Geofagia',
    'toxic-debris': 'Capa Tóxica',
    costar: 'Unísono',
    commander: 'Comandar',
    'cud-chew': 'Rumia',
    'armor-tail': 'Cola Armadura',
    'supreme-overlord': 'General Supremo',
    protosynthesis: 'Paleosíntesis',
    'quark-drive': 'Carga Cuark',
    'thermal-exchange': 'Termoconversión',
    'good-as-gold': 'Cuerpo Áureo',
    'tablets-of-ruin': 'Tablero Debacle',
    'sword-of-ruin': 'Espada Debacle',
    'vessel-of-ruin': 'Caldero Debacle',
    'beads-of-ruin': 'Abalorio Debacle',
    'orichalcum-pulse': 'Latido Oricalco',
    'hadron-engine': 'Motor Hadrónico',
    'supersweet-syrup': 'Néctar Dulce',
    hospitality: 'Hospitalidad',
    'toxic-chain': 'Cadena Tóxica',
    'tera-shift': 'Teracambio',
    'poison-puppeteer': 'Títere Tóxico',
    'parental-bond': 'Amor Filial',
    aerilate: 'Piel Celeste',
    'primordial-sea': 'Mar del Albor',
    'desolate-land': 'Tierra del Ocaso',
    'delta-stream': 'Ráfaga Delta',
    'surge-surfer': 'Cola Surf',
    'tangling-hair': 'Rizos Rebeldes',
    galvanize: 'Piel Eléctrica',
    'power-of-alchemy': 'Reacción Química',
    'battle-bond': 'Fuerte Afecto',
    'power-construct': 'Agrupamiento',
    neuroforce: 'Fuerza Cerebral',
    'pastel-veil': 'Velo Pastel',
    'quick-draw': 'Mano Rápida',
    'curious-medicine': 'Medicina Extraña',
    'gorilla-tactics': 'Monotema',
    mimicry: 'Mimetismo',
    'as-one-glastrier': 'Unidad Ecuestre',
    'as-one-spectrier': 'Unidad Ecuestre',
    'minds-eye': 'Ojo Mental',
    'tera-shell': 'Teracaparazón',
    'teraform-zero': 'Teraformación 0',
    'mega-sol': 'Megasolar',
    dragonize: 'Piel Dragontina',
    'piercing-drill': 'Turbotaladro',
    'spicy-spray': 'Salpicante',
  };

  public statMap: Record<string, string> = {
    hp: 'PS',
    attack: 'Ataque',
    defense: 'Defensa',
    'special-attack': 'Ataque Especial',
    'special-defense': 'Defensa Especial',
    speed: 'Velocidad'
  }

  public descriptionMap: Record<string, string> = {
    "The power of the Pokémon's ruinous beads lowers the Sp. Def stats of all Pokémon except itself.": "Reduce la Defensa Especial de todos los Pokemon en combate excepto el poseedor",
    "The power of the Pokémon's toxic chain may badly poison any target the Pokémon hits with a move": "Los ataques del poseedor pueden envenenar gravemente al objetivo",
    "The power of the Pokémon's ruinous vessel lowers the Sp. Atk stats of all Pokémon except itself.": "Reduce el Ataque Especial de todos los Pokemon en combate excepto el poseedor",
    "The Pokémon transforms into its Hero Form when it switches out.": "El Pokémon cambiará a su forma Heróica al ser relevado durante el combate",
    "Scatters poison spikes at the feet of the opposing team when the Pokémon takes damage from physical moves.": "Libera una capa de Púas Tóxicas hacia el enemigo al ser golpeado por un movimiento físico",
    "Boosts the Pokémon's most proficient stat on Electric Terrain or if the Pokémon is holding Booster Energy.": "Potencia su característica más alta en un Campo Eléctrico o al llevar equipado el objeto Energía Potenciadora",
    "The mysterious tail covering the Pokémon's head makes opponents unable to use priority moves against the Pokémon or its allies.": "Impide a los enemigos usar movimientos de alta prioridad contra el poseedor y sus aliados",
    "When the Pokémon enters a battle, it goes inside the mouth of an ally Dondozo if one is on the field. The Pokémon then issues commands from there.": "Al entrar en combate, se mete dentro de la boca de un Dondozo aliado, si lo hay, y le da órdenes desde ahí",
    "When an attack causes its HP to drop to half or less, the Pokémon gets angry. This lowers its Defense and Sp. Def stats but boosts its Attack, Sp. Atk, and Speed stats.": "Cuando sus PS se reducen a la mitad por un ataque, reduce sus defensas y aumenta sus ataques y velocidad",
    "Powers up slicing moves.": "Potencia los movimientos de corte",
    "A body of pure, solid gold gives the Pokémon full immunity to other Pokémon's status moves.": "Su cuerpo dorado otorga inmunidad a los movimientos de estado",
    "The Pokémon becomes charged when it takes damage, boosting the power of the next Electric-type move the Pokémon uses.": "Potencia su siguiente movimiento de tipo Eléctrico al recibir daño mediante un ataque",
    "Turns the ground into Grassy Terrain when the Pokémon is hit by an attack.": "Invoca un Campo de Hierba al recibir daño mediante un ataque",
    "The Pokémon becomes charged when it is hit by a wind move, boosting the power of the next Electric-type move the Pokémon uses.": "Potencia su siguiente movimiento de tipo Eléctrico al recibir daño mediante un movimiento basado en viento",
    "The power of the Pokémon's ruinous sword lowers the Defense stats of all Pokémon except itself.": "Reduce la Defensa de todos los Pokémon en combate excepto el poseedor",
    "When the Pokémon enters a battle, its Attack and Sp. Atk stats are slightly boosted for each of the allies in its party that have already been defeated.": "Potencia su Ataque y Ataque Especial según cuántos aliados han sido debilitados durante el combate",
    "If hit by a Ground-type move, the Pokémon has its HP restored instead of taking damage.": "Recupera PS al ser golpeado por un movimiento de tipo Tierra",
    "When the Pokémon enters a battle, it showers its ally with hospitality, restoring a small amount of the ally's HP": "Su hospitalidad hace que su aliado recupere PS cuando el poseedor entra en combate",
    "Turns the sunlight harsh when the Pokémon enters a battle. The ancient pulse thrumming through the Pokémon also boosts its Attack stat in harsh sunlight.": "Invoca un clima soleado al entrar en combate, y potencia su Ataque en dicho clima",
    "Even when the sunlight has not turned harsh, the Pokémon can use its moves as if the weather were harsh sunlight.": "El poseedor ejecuta sus movimientos como si estuviera en clima soleado",
    "Turns the ground into Electric Terrain when the Pokémon enters a battle. The futuristic engine within the Pokémon also boosts its Sp. Atk stat on Electric Terrain.": "Invoca un Campo Eléctrico al entrar en combate, y potencia su Ataque Especial en dicho campo",
    "Lowers the evasion of opposing Pokémon by 1 stage when first sent into battle": "Reduce la Evasión del oponente cuando entra en combate por primera vez",
    "The Pokémon ignores changes to opponents' evasiveness, its accuracy can't be lowered, and it can hit Ghost types with Normal-type and Fighting-type moves": "Ignora los cambios en la Evasión del objetivo, impide que su Precisión pueda ser reducida, y puede golpear a los Pokémon de tipo Fantasma con movimientos de tipo Normal o Lucha",
    "Contact with the Pokémon changes the attacker's Ability to Lingering Aroma.": "Establecer contacto con el poseedor provoca que la habilidad del atacante cambie a Olor Persistente",
    "If an opponent's stat is boosted, the Pokémon seizes the opportunity to boost the same stat for itself.": "El poseedor aprovecha la oportunidad y, cuando un oponente aumenta sus características, aumenta las suyas también",
    "Boosts the Pokémon's most proficient stat in harsh sunlight or if the Pokémon is holding Booster Energy.": "Potencia su característica más alta en clima soleado o al llevar equipado el objeto Energía Potenciadora",
    "Boosts the Pokémon’s Attack stat if intimidated. Moves and items that would force the Pokémon to switch out also fail to work.": "Potencia su Ataque si es objetivo de Intimidación. Los movimientos y objetos que provocan cambio de Pokémon tampoco funcionan",
    "The Pokémon's Normal-type moves become Dragon-type moves and their power is boosted by 20%.": "Convierte los movimientos de tipo Normal en tipo Dragón y aumenta su potencia",
    "The Pokémon will always act more slowly when using status moves, but these moves will be unimpeded by the Ability of the target.": "Al usar un movimiento de estado, el poseedor realizará su movimiento en último lugar, pero ignora la habilidad del objetivo",
    "When the Pokémon eats a Berry, it will regurgitate that Berry at the end of the next turn and eat it one more time.": "Al comer una baya, la regurgita en el siguiente turno para volvérsela a comer",
    "The Pokémon's pure salt protects it from status conditions and halves the damage taken from Ghost-type moves.": "Su sal pura protege al poseedor de cambios de estado y reduce a la mitad el daño recibido por movimientos de tipo Fantasma",
    "When the Pokémon takes damage from a move, it burns the attacker.": "Provoca una quemadura a su atacante al recibir daño directo",
    "Boosts the Pokémon's Attack stat if Tailwind takes effect or if the Pokémon is hit by a wind move. The Pokémon also takes no damage from wind moves.": "Potencia su Ataque durante un Viento Afín o al ser objetivo de un movimiento basado en viento, anulando el daño recibido por dichos movimientos",
    "The power of the Pokémon's ruinous wooden tablets lowers the Attack stats of all Pokémon except itself.": "Reduce el Ataque de todos los Pokémon en combate excepto el poseedor",
    "When the Pokémon enters a battle, it absorbs the energy around itself and transforms into its Terastal Form.": "Cambia a su forma Teracristal al entrar en combate",
    "The Pokémon's shell contains the powers of each type. All damage-dealing moves that hit the Pokémon when its HP is full will not be very effective.": "Si sus PS están al máximo, recibe daño poco eficaz de cualquier movimiento de daño directo",
    "When Terapagos changes into its Stellar Form, it uses its hidden powers to eliminate all effects of weather and terrain, reducing them to zero.": "Cuando Terapagos cambia a su forma Estelar, elimina todos los efectos de clima y campos",
    "Boosts the Attack stat when the Pokémon is hit by a Fire-type move. The Pokémon also cannot be burned.": "Potencia su Ataque al ser golpeado por un movimiento de tipo Fuego, y además no puede sufrir quemaduras",
    "Pokémon poisoned by Pecharunt's moves will also become confused.": "Causa confusión a cualquier oponente que envenene",
    "Powers up Rock-type moves.": "Potencia los movimientos de tipo Roca",
    "When the Pokémon uses contact moves, it can hit even targets that are protecting themselves, dealing 1/4 of the damage that the move would otherwise deal. Everything aside from the target's protective effects is still triggered.": "Permite al poseedor golpear a objetivos que hayan usado movimientos de protección, realizando solo un 25% de daño a dichos objetivos. Los efectos causados por golpear las protecciones se seguirán activando",
    "When the Pokémon enters a battle, it copies an ally's stat changes.": "Copia los cambios de características de los aliados al entrar en combate"
  }

  public moveMap: Record<string, string> = {
    pound: 'Destructor',
    'karate-chop': 'Golpe Kárate',
    'double-slap': 'Doble Bofetón',
    'comet-punch': 'Puño Cometa',
    'mega-punch': 'Megapuño',
    'pay-day': 'Día de Pago',
    'fire-punch': 'Puño Fuego',
    'ice-punch': 'Puño Hielo',
    'thunder-punch': 'Puño Trueno',
    scratch: 'Arañazo',
    'vice-grip': 'Agarre',
    guillotine: 'Guillotina',
    'razor-wind': 'Viento Cortante',
    'swords-dance': 'Danza Espada',
    cut: 'Corte',
    gust: 'Tornado',
    'wing-attack': 'Ataque Ala',
    whirlwind: 'Remolino',
    fly: 'Vuelo',
    bind: 'Atadura',
    slam: 'Atizar',
    'vine-whip': 'Látigo Cepa',
    stomp: 'Pisotón',
    'double-kick': 'Doble Patada',
    'mega-kick': 'Mega Patada',
    'jump-kick': 'Patada Salto',
    'rolling-kick': 'Patada Giro',
    'sand-attack': 'Ataque Arena',
    headbutt: 'Golpe Cabeza',
    'horn-attack': 'Cornada',
    'fury-attack': 'Ataque Furia',
    'horn-drill': 'Taladro',
    tackle: 'Placaje',
    'body-slam': 'Golpe Cuerpo',
    wrap: 'Constricción',
    'take-down': 'Derribo',
    thrash: 'Saña',
    'double-edge': 'Doble Filo',
    'tail-whip': 'Látigo',
    'poison-sting': 'Picotazo Veneno',
    twineedle: 'Doble Ataque',
    'pin-missile': 'Pin Misil',
    leer: 'Malicioso',
    bite: 'Mordisco',
    growl: 'Gruñido',
    roar: 'Rugido',
    sing: 'Canto',
    supersonic: 'Supersónico',
    'sonic-boom': 'Bomba Sónica',
    disable: 'Anulación',
    acid: 'Ácido',
    ember: 'Ascuas',
    flamethrower: 'Lanzallamas',
    mist: 'Neblina',
    'water-gun': 'Pistola Agua',
    'hydro-pump': 'Hidrobomba',
    surf: 'Surf',
    'ice-beam': 'Rayo Hielo',
    blizzard: 'Ventisca',
    psybeam: 'Psicorrayo',
    'bubble-beam': 'Rayo Burbuja',
    'aurora-beam': 'Rayo Aurora',
    'hyper-beam': 'Hiperrayo',
    peck: 'Picotazo',
    'drill-peck': 'Pico Taladro',
    submission: 'Sumisión',
    'low-kick': 'Patada Baja',
    counter: 'Contraataque',
    'seismic-toss': 'Sísmico',
    strength: 'Fuerza',
    absorb: 'Absorber',
    'mega-drain': 'Megaagotar',
    'leech-seed': 'Drenadoras',
    growth: 'Desarrollo',
    'razor-leaf': 'Hoja Afilada',
    'solar-beam': 'Rayo Solar',
    'poison-powder': 'Polvo Veneno',
    'stun-spore': 'Paralizador',
    'sleep-powder': 'Somnífero',
    'petal-dance': 'Danza Pétalo',
    'string-shot': 'Disparo Demora',
    'dragon-rage': 'Furia Dragón',
    'fire-spin': 'Giro Fuego',
    'thunder-shock': 'Impactrueno',
    thunderbolt: 'Rayo',
    'thunder-wave': 'Onda Trueno',
    thunder: 'Trueno',
    'rock-throw': 'Lanzarrocas',
    earthquake: 'Terremoto',
    fissure: 'Fisura',
    dig: 'Excavar',
    toxic: 'Tóxico',
    confusion: 'Confusión',
    psychic: 'Psíquico',
    hypnosis: 'Hipnosis',
    meditate: 'Meditación',
    agility: 'Agilidad',
    'quick-attack': 'Ataque Rápido',
    rage: 'Furia',
    teleport: 'Teletransporte',
    'night-shade': 'Tinieblas',
    mimic: 'Mimético',
    screech: 'Chirrido',
    'double-team': 'Doble Equipo',
    recover: 'Recuperación',
    harden: 'Fortaleza',
    minimize: 'Reducción',
    smokescreen: 'Pantalla de Humo',
    'confuse-ray': 'Rayo Confuso',
    withdraw: 'Refugio',
    'defense-curl': 'Rizo Defensa',
    barrier: 'Barrera',
    'light-screen': 'Pantalla de Luz',
    haze: 'Niebla',
    reflect: 'Reflejo',
    'focus-energy': 'Foco Energía',
    bide: 'Venganza',
    metronome: 'Metrónomo',
    'mirror-move': 'Espejo',
    'self-destruct': 'Autodestrucción',
    'egg-bomb': 'Bomba Huevo',
    lick: 'Lengüetazo',
    smog: 'Polución',
    sludge: 'Residuos',
    'bone-club': 'Hueso Palo',
    'fire-blast': 'Llamarada',
    waterfall: 'Cascada',
    clamp: 'Tenaza',
    swift: 'Meteoros',
    'skull-bash': 'Cabezazo',
    'spike-cannon': 'Clavo Cañón',
    constrict: 'Restricción',
    amnesia: 'Amnesia',
    kinesis: 'Kinético',
    'soft-boiled': 'Ovocuración',
    'high-jump-kick': 'Patada Salto Alta',
    glare: 'Deslumbrar',
    'dream-eater': 'Comesueños',
    'poison-gas': 'Gas Venenoso',
    barrage: 'Bombardeo',
    'leech-life': 'Chupavidas',
    'lovely-kiss': 'Beso Amoroso',
    'sky-attack': 'Ataque Aéreo',
    transform: 'Transformación',
    bubble: 'Burbuja',
    'dizzy-punch': 'Puño Mareo',
    spore: 'Espora',
    flash: 'Destello',
    psywave: 'Psicoonda',
    splash: 'Salpicadura',
    'acid-armor': 'Armadura Ácida',
    crabhammer: 'Martillazo',
    explosion: 'Explosión',
    'fury-swipes': 'Golpes Furia',
    bonemerang: 'Huesomerang',
    rest: 'Descanso',
    'rock-slide': 'Avalancha',
    'hyper-fang': 'Hipercolmillo',
    sharpen: 'Afilar',
    conversion: 'Conversión',
    'tri-attack': 'Triataque',
    'super-fang': 'Superdiente',
    slash: 'Cuchillada',
    substitute: 'Sustituto',
    struggle: 'Forcejeo',
    sketch: 'Esquema',
    'triple-kick': 'Triple Patada',
    thief: 'Ladrón',
    'spider-web': 'Telaraña',
    'mind-reader': 'Telépata',
    nightmare: 'Pesadilla',
    'flame-wheel': 'Rueda Fuego',
    snore: 'Ronquido',
    curse: 'Maldición',
    flail: 'Azote',
    'conversion-2': 'Conversión2',
    aeroblast: 'Aerochorro',
    'cotton-spore': 'Esporagodón',
    reversal: 'Inversión',
    spite: 'Rencor',
    'powder-snow': 'Nieve Polvo',
    protect: 'Protección',
    'mach-punch': 'Ultrapuño',
    'scary-face': 'Cara Susto',
    'feint-attack': 'Finta',
    'sweet-kiss': 'Beso Dulce',
    'belly-drum': 'Tambor',
    'sludge-bomb': 'Bomba Lodo',
    'mud-slap': 'Bofetón Lodo',
    octazooka: 'Pulpocañón',
    spikes: 'Púas',
    'zap-cannon': 'Electrocañón',
    foresight: 'Profecía',
    'destiny-bond': 'Mismo Destino',
    'perish-song': 'Canto Mortal',
    'icy-wind': 'Viento Hielo',
    detect: 'Detección',
    'bone-rush': 'Ataque Óseo',
    'lock-on': 'Fijar Blanco',
    outrage: 'Enfado',
    sandstorm: 'Tormenta Arena',
    'giga-drain': 'Gigadrenado',
    endure: 'Aguante',
    charm: 'Encanto',
    rollout: 'Rodar',
    'false-swipe': 'Falso Tortazo',
    swagger: 'Contoneo',
    'milk-drink': 'Batido',
    spark: 'Chispa',
    'fury-cutter': 'Corte Furia',
    'steel-wing': 'Ala de Acero',
    'mean-look': 'Mal de Ojo',
    attract: 'Atracción',
    'sleep-talk': 'Sonámbulo',
    'heal-bell': 'Cascabel Cura',
    return: 'Retribución',
    present: 'Presente',
    frustration: 'Frustración',
    safeguard: 'Velo Sagrado',
    'pain-split': 'Divide Dolor',
    'sacred-fire': 'Fuego Sagrado',
    magnitude: 'Magnitud',
    'dynamic-punch': 'Puño Dinámico',
    megahorn: 'Megacuerno',
    'dragon-breath': 'Dragoaliento',
    'baton-pass': 'Relevo',
    encore: 'Otra Vez',
    pursuit: 'Persecución',
    'rapid-spin': 'Giro Rápido',
    'sweet-scent': 'Dulce Aroma',
    'iron-tail': 'Cola Férrea',
    'metal-claw': 'Garra Metal',
    'vital-throw': 'Llave Vital',
    'morning-sun': 'Sol Matinal',
    synthesis: 'Síntesis',
    moonlight: 'Luz Lunar',
    'hidden-power': 'Poder Oculto',
    'cross-chop': 'Tajo Cruzado',
    twister: 'Ciclón',
    'rain-dance': 'Danza Lluvia',
    'sunny-day': 'Día Soleado',
    crunch: 'Triturar',
    'mirror-coat': 'Manto Espejo',
    'psych-up': 'Autosugestión',
    'extreme-speed': 'Velocidad Extrema',
    'ancient-power': 'Poder Pasado',
    'shadow-ball': 'Bola Sombra',
    'future-sight': 'Premonición',
    'rock-smash': 'Golpe Roca',
    whirlpool: 'Torbellino',
    'beat-up': 'Paliza',
    'fake-out': 'Sorpresa',
    uproar: 'Alboroto',
    stockpile: 'Reserva',
    'spit-up': 'Escupir',
    swallow: 'Tragar',
    'heat-wave': 'Onda Ígnea',
    hail: 'Granizo',
    torment: 'Tormento',
    flatter: 'Camelo',
    'will-o-wisp': 'Fuego Fatuo',
    memento: 'Legado',
    facade: 'Imagen',
    'focus-punch': 'Puño Certero',
    'smelling-salts': 'Estímulo',
    'follow-me': 'Señuelo',
    'nature-power': 'Adaptación',
    charge: 'Carga',
    taunt: 'Mofa',
    'helping-hand': 'Refuerzo',
    trick: 'Truco',
    'role-play': 'Imitación',
    wish: 'Deseo',
    assist: 'Ayuda',
    ingrain: 'Arraigo',
    superpower: 'Fuerza Bruta',
    'magic-coat': 'Capa Mágica',
    recycle: 'Reciclaje',
    revenge: 'Desquite',
    'brick-break': 'Demolición',
    yawn: 'Bostezo',
    'knock-off': 'Desarme',
    endeavor: 'Esfuerzo',
    eruption: 'Estallido',
    'skill-swap': 'Intercambio',
    imprison: 'Sellar',
    refresh: 'Alivio',
    grudge: 'Rabia',
    snatch: 'Robo',
    'secret-power': 'Daño Secreto',
    dive: 'Buceo',
    'arm-thrust': 'Empujón',
    camouflage: 'Camuflaje',
    'tail-glow': 'Luminicola',
    'luster-purge': 'Resplandor',
    'mist-ball': 'Bola Neblina',
    'feather-dance': 'Danza Pluma',
    'teeter-dance': 'Danza Caos',
    'blaze-kick': 'Patada Ígnea',
    'mud-sport': 'Chapoteo Lodo',
    'ice-ball': 'Bola Hielo',
    'needle-arm': 'Brazo Pincho',
    'slack-off': 'Relajo',
    'hyper-voice': 'Vozarrón',
    'poison-fang': 'Colmillo Veneno',
    'crush-claw': 'Garra Brutal',
    'blast-burn': 'Anillo Ígneo',
    'hydro-cannon': 'Hidrocañón',
    'meteor-punch': 'Puño Meteoro',
    astonish: 'Impresionar',
    'weather-ball': 'Meteorobola',
    aromatherapy: 'Aromaterapia',
    'fake-tears': 'Llanto Falso',
    'air-cutter': 'Aire Afilado',
    overheat: 'Sofoco',
    'odor-sleuth': 'Rastreo',
    'rock-tomb': 'Tumba Rocas',
    'silver-wind': 'Viento Plata',
    'metal-sound': 'Eco Metálico',
    'grass-whistle': 'Silbato',
    tickle: 'Cosquillas',
    'cosmic-power': 'Masa Cósmica',
    'water-spout': 'Salpicar',
    'signal-beam': 'Rayo Señal',
    'shadow-punch': 'Puño Sombra',
    extrasensory: 'Paranormal',
    'sky-uppercut': 'Gancho Alto',
    'sand-tomb': 'Bucle Arena',
    'sheer-cold': 'Frío Polar',
    'muddy-water': 'Agua Lodosa',
    'bullet-seed': 'Semilladora',
    'aerial-ace': 'Golpe Aéreo',
    'icicle-spear': 'Carámbano',
    'iron-defense': 'Defensa Férrea',
    block: 'Bloqueo',
    howl: 'Aullido',
    'dragon-claw': 'Garra Dragón',
    'frenzy-plant': 'Planta Feroz',
    'bulk-up': 'Corpulencia',
    bounce: 'Bote',
    'mud-shot': 'Disparo Lodo',
    'poison-tail': 'Cola Veneno',
    covet: 'Antojo',
    'volt-tackle': 'Placaje Eléctrico',
    'magical-leaf': 'Hoja Mágica',
    'water-sport': 'Hidrochorro',
    'calm-mind': 'Paz Mental',
    'leaf-blade': 'Hoja Aguda',
    'dragon-dance': 'Danza Dragón',
    'rock-blast': 'Pedrada',
    'shock-wave': 'Onda Voltio',
    'water-pulse': 'Hidropulso',
    'doom-desire': 'Deseo Oculto',
    'psycho-boost': 'Psicoataque',
    roost: 'Respiro',
    gravity: 'Gravedad',
    'miracle-eye': 'Gran Ojo',
    'wake-up-slap': 'Espabila',
    'hammer-arm': 'Machada',
    'gyro-ball': 'Giro Bola',
    'healing-wish': 'Deseo Cura',
    brine: 'Salmuera',
    'natural-gift': 'Don Natural',
    feint: 'Amago',
    pluck: 'Picoteo',
    tailwind: 'Viento Afín',
    acupressure: 'Acupresión',
    'metal-burst': 'Represión Metal',
    'u-turn': 'Ida y Vuelta',
    'close-combat': 'A Bocajarro',
    payback: 'Vendetta',
    assurance: 'Buena Baza',
    embargo: 'Embargo',
    fling: 'Lanzamiento',
    'psychoshift': 'Psicocambio',
    'trump-card': 'As Oculto',
    'heal-block': 'Anticura',
    'wring-out': 'Estrujón',
    'power-trick': 'Truco Fuerza',
    'gastro-acid': 'Bilis',
    'lucky-chant': 'Conjuro',
    'me-first': 'Yo Primero',
    copycat: 'Copión',
    'power-swap': 'Cambiafuerza',
    'guard-swap': 'Cambiadefensa',
    punishment: 'Castigo',
    'last-resort': 'Última Baza',
    'worry-seed': 'Abatidoras',
    'sucker-punch': 'Golpe Bajo',
    'toxic-spikes': 'Púas Tóxicas',
    'heart-swap': 'Cambiaalmas',
    'aqua-ring': 'Acua Aro',
    'magnet-rise': 'Levitón',
    'flare-blitz': 'Envite Ígneo',
    'force-palm': 'Palmeo',
    'aura-sphere': 'Esfera Aural',
    'rock-polish': 'Pulimento',
    'poison-jab': 'Puya Nociva',
    'dark-pulse': 'Pulso Umbrío',
    'night-slash': 'Tajo Umbrío',
    'aqua-tail': 'Acua Cola',
    'seed-bomb': 'Bomba Germen',
    'air-slash': 'Tajo Aéreo',
    'x-scissor': 'Tijera X',
    'bug-buzz': 'Zumbido',
    'dragon-pulse': 'Pulso Dragón',
    'dragon-rush': 'Carga Dragón',
    'power-gem': 'Joya de Luz',
    'drain-punch': 'Puño Drenaje',
    'vacuum-wave': 'Onda Vacío',
    'focus-blast': 'Onda Certera',
    'energy-ball': 'Energibola',
    'brave-bird': 'Pájaro Osado',
    'earth-power': 'Tierra Viva',
    switcheroo: 'Trapicheo',
    'giga-impact': 'Giga Impacto',
    'nasty-plot': 'Maquinación',
    'bullet-punch': 'Puño Bala',
    avalanche: 'Alud',
    'ice-shard': 'Esquirla Helada',
    'shadow-claw': 'Garra Umbría',
    'thunder-fang': 'Colmillo Rayo',
    'ice-fang': 'Colmillo Hielo',
    'fire-fang': 'Colmillo Ígneo',
    'shadow-sneak': 'Sombra Vil',
    'mud-bomb': 'Bomba Fango',
    'psycho-cut': 'Psicocorte',
    'zen-headbutt': 'Cabezazo Zen',
    'mirror-shot': 'Disparo Espejo',
    'flash-cannon': 'Foco Resplandor',
    'rock-climb': 'Treparrocas',
    defog: 'Despejar',
    'trick-room': 'Espacio Raro',
    'draco-meteor': 'Cometa Draco',
    discharge: 'Chispazo',
    'lava-plume': 'Humareda',
    'leaf-storm': 'Lluevehojas',
    'power-whip': 'Latigazo',
    'rock-wrecker': 'Romperrocas',
    'cross-poison': 'Veneno X',
    'gunk-shot': 'Lanzamugre',
    'iron-head': 'Cabeza de Hierro',
    'magnet-bomb': 'Bomba Imán',
    'stone-edge': 'Roca Afilada',
    captivate: 'Seducción',
    'stealth-rock': 'Trampa Rocas',
    'grass-knot': 'Hierba Lazo',
    chatter: 'Cháchara',
    judgment: 'Sentencia',
    'bug-bite': 'Picadura',
    'charge-beam': 'Rayo Carga',
    'wood-hammer': 'Mazazo',
    'aqua-jet': 'Acua Jet',
    'attack-order': 'Al Ataque',
    'defend-order': 'A Defender',
    'heal-order': 'Auxilio',
    'head-smash': 'Testarazo',
    'double-hit': 'Doble Golpe',
    'roar-of-time': 'Distorsión',
    'spacial-rend': 'Corte Vación',
    'lunar-dance': 'Danza Lunar',
    'crush-grip': 'Agarrón',
    'magma-storm': 'Lluvia Ígnea',
    'dark-void': 'Brecha Negra',
    'seed-flare': 'Fulgor Semilla',
    'ominous-wind': 'Viento Aciago',
    'shadow-force': 'Golpe Umbrío',
    'hone-claws': 'Afilagarras',
    'wide-guard': 'Vastaguardia',
    'guard-split': 'Isoguardia',
    'power-split': 'Isofuerza',
    'wonder-room': 'Zona Extraña',
    psyshock: 'Psicocarga',
    venoshock: 'Carga Tóxica',
    autotomize: 'Aligerar',
    'rage-powder': 'Polvo Ira',
    telekinesis: 'Telequinesis',
    'magic-room': 'Zona Mágica',
    'smack-down': 'Antiaéreo',
    'storm-throw': 'Llave Corsé',
    'flame-burst': 'Pirotecnia',
    'sludge-wave': 'Onda Tóxica',
    'quiver-dance': 'Danza Aleteo',
    'heavy-slam': 'Cuerpo Pesado',
    synchronoise: 'Sincrorruido',
    'electro-ball': 'Bola Voltio',
    soak: 'Empapar',
    'flame-charge': 'Nitrocarga',
    coil: 'Enrosque',
    'low-sweep': 'Puntapié',
    'acid-spray': 'Bomba Ácida',
    'foul-play': 'Juego Sucio',
    'simple-beam': 'Onda Simple',
    entrainment: 'Danza Amiga',
    'after-you': 'Cede Paso',
    round: 'Canon',
    'echoed-voice': 'Eco Voz',
    'chip-away': 'Guardia Baja',
    'clear-smog': 'Niebla Clara',
    'stored-power': 'Poder Reserva',
    'quick-guard': 'Anticipo',
    'ally-switch': 'Cambio de Banda',
    scald: 'Escaldar',
    'shell-smash': 'Rompecoraza',
    'heal-pulse': 'Pulso Cura',
    hex: 'Infortunio',
    'sky-drop': 'Caída Libre',
    'shift-gear': 'Cambio de Marcha',
    'circle-throw': 'Llave Giro',
    incinerate: 'Calcinación',
    quash: 'Último Lugar',
    acrobatics: 'Acróbata',
    'reflect-type': 'Clonatipo',
    retaliate: 'Represalia',
    'final-gambit': 'Sacrificio',
    bestow: 'Ofrenda',
    inferno: 'Infierno',
    'water-pledge': 'Voto Agua',
    'fire-pledge': 'Voto Fuego',
    'grass-pledge': 'Voto Planta',
    'volt-switch': 'Voltiocambio',
    'struggle-bug': 'Estoicismo',
    bulldoze: 'Terratemblor',
    'frost-breath': 'Vaho Gélido',
    'dragon-tail': 'Cola Dragón',
    'work-up': 'Avivar',
    electroweb: 'Electrotela',
    'wild-charge': 'Voltio Cruel',
    'drill-run': 'Taladradora',
    'dual-chop': 'Golpe Bis',
    'heart-stamp': 'Arrumaco',
    'horn-leech': 'Asta Drenaje',
    'sacred-sword': 'Espada Santa',
    'razor-shell': 'Concha Filo',
    'heat-crash': 'Golpe Calor',
    'leaf-tornado': 'Ciclón de Hojas',
    'steam-roller': 'Rodillo de Púas',
    'cotton-guard': 'Rizo Algodón',
    'night-daze': 'Pulso Noche',
    psystrike: 'Onda Mental',
    'tail-slap': 'Plumerazo',
    hurricane: 'Vendaval',
    'head-charge': 'Ariete',
    'gear-grind': 'Rueda Doble',
    'searing-shot': 'Bomba Ígnea',
    'techno-blast': 'Tecno Shock',
    'relic-song': 'Canto Arcaico',
    'secret-sword': 'Sable Místico',
    glaciate: 'Mundo Gélido',
    'bolt-strike': 'Ataque Fulgor',
    'blue-flare': 'Llama Azul',
    'fiery-dance': 'Danza Llama',
    'freeze-shock': 'Rayo Gélido',
    'ice-burn': 'Llama Gélida',
    snarl: 'Alarido',
    'icicle-crash': 'Chuzos',
    'v-create': 'V de Fuego',
    'fusion-flare': 'Llama Fusión',
    'fusion-bolt': 'Rayo Fusión',
    'flying-press': 'Plancha Voladora',
    'mat-block': 'Escudo Tatami',
    belch: 'Eructo',
    rototiller: 'Fertilizante',
    'sticky-web': 'Red Viscosa',
    'fell-stinger': 'Aguijón Letal',
    'phantom-force': 'Golpe Fantasma',
    'trick-or-treat': 'Halloween',
    'noble-roar': 'Rugido de Guerra',
    'ion-deluge': 'Cortina Plasma',
    'parabolic-charge': 'Carga Parábola',
    'forests-curse': 'Condena Silvana',
    'petal-blizzard': 'Tormenta Floral',
    'freeze-dry': 'Liofilización',
    'disarming-voice': 'Voz Cautivadora',
    'parting-shot': 'Última Palabra',
    'topsy-turvy': 'Reversión',
    'draining-kiss': 'Beso Drenaje',
    'crafty-shield': 'Truco Defensa',
    'flower-shield': 'Defensa Floral',
    'grassy-terrain': 'Campo de Hierba',
    'misty-terrain': 'Campo de Niebla',
    electrify: 'Electrificación',
    'play-rough': 'Carantoña',
    'fairy-wind': 'Viento Feérico',
    moonblast: 'Fuerza Lunar',
    boomburst: 'Estruendo',
    'fairy-lock': 'Cerrojo Feérico',
    'kings-shield': 'Escudo Real',
    'play-nice': 'Camaradería',
    confide: 'Confidencia',
    'diamond-storm': 'Tormenta de Diamantes',
    'steam-eruption': 'Chorro de Vapor',
    'hyperspace-hole': 'Paso Dimensional',
    'water-shuriken': 'Shuriken de Agua',
    'mystical-fire': 'Llama Mística',
    'spiky-shield': 'Barrera Espinosa',
    'aromatic-mist': 'Niebla Aromática',
    'eerie-impulse': 'Onda Anómala',
    'venom-drench': 'Trampa Venenosa',
    powder: 'Polvo Explosivo',
    geomancy: 'Geocontrol',
    'magnetic-flux': 'Aura Magnética',
    'happy-hour': 'Paga Extra',
    'electric-terrain': 'Campo Eléctrico',
    'dazzling-gleam': 'Brillo Mágico',
    celebrate: 'Celebración',
    'hold-hands': 'Manos Juntas',
    'baby-doll-eyes': 'Ojitos Tiernos',
    nuzzle: 'Moflete Estático',
    'hold-back': 'Clemencia',
    infestation: 'Acoso',
    'power-up-punch': 'Puño Incremento',
    'oblivion-wing': 'Ala Mortífera',
    'thousand-arrows': 'Mil Flechas',
    'thousand-waves': 'Mil Temblores',
    'lands-wrath': 'Fuerza Telúrica',
    'light-of-ruin': 'Luz Aniquiladora',
    'origin-pulse': 'Pulso Primigenio',
    'precipice-blades': 'Filo del Abismo',
    'dragon-ascent': 'Ascenso Draco',
    'hyperspace-fury': 'Cerco Dimensión',
    'breakneck-blitz--physical': 'Carrera Arrolladora',
    'breakneck-blitz--special': 'Carrera Arrolladora',
    'all-out-pummeling--physical': 'Ráfaga Demoledora',
    'all-out-pummeling--special': 'Ráfaga Demoledora',
    'supersonic-skystrike--physical': 'Picado Supersónico',
    'supersonic-skystrike--special': 'Picado Supersónico',
    'acid-downpour--physical': 'Diluvio Corrosivo',
    'acid-downpour--special': 'Diluvio Corrosivo',
    'tectonic-rage--physical': 'Barrena Telúrica',
    'tectonic-rage--special': 'Barrena Telúrica',
    'continental-crush--physical': 'Aplastamiento Gigalítico',
    'continental-crush--special': 'Aplastamiento Gigalítico',
    'savage-spin-out--physical': 'Guadaña Sedosa',
    'savage-spin-out--special': 'Guadaña Sedosa',
    'never-ending-nightmare--physical': 'Presa Espectral',
    'never-ending-nightmare--special': 'Presa Espectral',
    'corkscrew-crash--physical': 'Hélice Trepanadora',
    'corkscrew-crash--special': 'Hélice Trepanadora',
    'inferno-overdrive--physical': 'Hecatombe Pírica',
    'inferno-overdrive--special': 'Hecatombe Pírica',
    'hydro-vortex--physical': 'Hidrovórtice Abisal',
    'hydro-vortex--special': 'Hidrovórtice Abisal',
    'bloom-doom--physical': 'Megatón Floral',
    'bloom-doom--special': 'Megatón Floral',
    'gigavolt-havoc--physical': 'Gigavoltio Destructor',
    'gigavolt-havoc--special': 'Gigavoltio Destructor',
    'shattered-psyche--physical': 'Disruptor Psíquico',
    'shattered-psyche--special': 'Disruptor Psíquico',
    'subzero-slammer--physical': 'Crioaliento Despiadado',
    'subzero-slammer--special': 'Crioaliento Despiadado',
    'devastating-drake--physical': 'Dracoaliento Devastador',
    'devastating-drake--special': 'Dracoaliento Devastador',
    'black-hole-eclipse--physical': 'Agujero Negro Aniquilador',
    'black-hole-eclipse--special': 'Agujero Negro Aniquilador',
    'twinkle-tackle--physical': 'Arrumaco Sideral',
    'twinkle-tackle--special': 'Arrumaco Sideral',
    catastropika: 'Pikavoltio Letal',
    'shore-up': 'Recogearena',
    'first-impression': 'Escaramuza',
    'baneful-bunker': 'Búnker',
    'spirit-shackle': 'Puntada Sombría',
    'darkest-lariat': 'Lariat Oscuro',
    'sparkling-aria': 'Aria Burbuja',
    'ice-hammer': 'Martillo Hielo',
    'floral-healing': 'Cura Floral',
    'high-horsepower': 'Fuerza Equina',
    'strength-sap': 'Absorbefuerza',
    'solar-blade': 'Cuchilla Solar',
    leafage: 'Follaje',
    spotlight: 'Foco',
    'toxic-thread': 'Hilo Venenoso',
    'laser-focus': 'Aguzar',
    'gear-up': 'Piñón Auxiliar',
    'throat-chop': 'Golpe Mordaza',
    'pollen-puff': 'Bola de Polen',
    'anchor-shot': 'Anclaje',
    'psychic-terrain': 'Campo Psíquico',
    lunge: 'Plancha',
    'fire-lash': 'Látigo Ígneo',
    'power-trip': 'Chulería',
    'burn-up': 'Llama Final',
    'speed-swap': 'Cambiavelocidad',
    'smart-strike': 'Cuerno Certero',
    purify: 'Purificación',
    'revelation-dance': 'Danza Despertar',
    'core-enforcer': 'Núcleo Castigo',
    'trop-kick': 'Patada Tropical',
    instruct: 'Mandato',
    'beak-blast': 'Pico Cañón',
    'clanging-scales': 'Fragor Escamas',
    'dragon-hammer': 'Martillo Dragón',
    'brutal-swing': 'Giro Vil',
    'aurora-veil': 'Velo Aurora',
    'sinister-arrow-raid': 'Aluvión de Flechas Sombrías',
    'malicious-moonsault': 'Hiperplancha Oscura',
    'oceanic-operetta': 'Sinfonía de la Diva Marina',
    'guardian-of-alola': 'Cólera del Guardián',
    'soul-stealing-7-star-strike': 'Constelación Robaalmas',
    'stoked-sprksurfer': 'Surfeo Galvánico',
    'pulverizing-pancake': 'Arrojo Intempestivo',
    'extreme-evoboost': 'Novena Potencia',
    'genesis-supernova': 'Supernova Original',
    'shell-trap': 'Coraza Trampa',
    'fleur-cannon': 'Cañón Floral',
    'psychic-fangs': 'Psicocolmillo',
    'stomping-tantrum': 'Pataleta',
    'shadow-bone': 'Hueso Sombrío',
    'accelerock': 'Roca Veloz',
    'liquidation': 'Hidroariete',
    'prismatic-laser': 'Láser Prisma',
    'spectral-thief': 'Robasombra',
    'sunsteel-strike': 'Meteoimpacto',
    'moongeist-beam': 'Rayo Umbrío',
    'tearful-look': 'Ojos Llorosos',
    'zing-zap': 'Electropunzada',
    'natures-madness': 'Furia Natural',
    'multi-attack': 'Multiataque',
    '10-000-000-volt-thunderbolt': 'Gigarrayo Fulminante',
    'mind-blown': 'Cabeza Sorpresa',
    'plasma-fists': 'Puños Plasma',
    'photon-geyser': 'Géiser Fotónico',
    'light-that-burns-the-sky': 'Fotodestrucción Apocalíptica',
    'searing-sunrize-smash': 'Embestida Solar',
    'menacing-moonraze-maelstrom': 'Deflagración Lunar',
    'lets-snuggle-forever': 'Somanta Amistosa',
    'splintered-stormshards': 'Tempestad Rocosa',
    'clangorous-soulblaze': 'Estruendo Implacable',
    'zippy-zap': 'Pikaturbo',
    'splishy-splash': 'Salpikasurf',
    'floaty-fall': 'Pikapicado',
    'pika-papow': 'Pikatormenta',
    'bouncy-bubble': 'Vapodrenaje',
    'buzzy-buzz': 'Joltioparálisis',
    'sizzly-slide': 'Flarembestida',
    'glitzy-glow': 'Espeaura',
    'baddy-bad': 'Umbreozona',
    'sappy-seed': 'Leafitobombas',
    'freezy-frost': 'Glaceoprisma',
    'sparkly-swirl': 'Sylveotornado',
    'veevee-volley': 'Eevimpacto',
    'double-iron-bash': 'Ferropuño Doble',
    'max-guard': 'Maxibarrera',
    'dynamax-cannon': 'Cañón Dinamax',
    'snipe-shot': 'Disparo Certero',
    'jaw-lock': 'Presa Maxilar',
    'stuff-cheeks': 'Atiborramiento',
    'no-retreat': 'Bastión Final',
    'tar-shot': 'Alquitranazo',
    'magic-powder': 'Polvo Mágico',
    'dragon-darts': 'Dracoflechas',
    teatime: 'Hora del Té',
    octolock: 'Octopresa',
    'bolt-beak': 'Electropico',
    'fishious-rend': 'Branquibocado',
    'court-change': 'Cambio de Cancha',
    'max-flare': 'Maxignición',
    'max-flutterby': 'Maxinsecto',
    'max-lightning': 'Maxitormenta',
    'max-strike': 'Maxiataque',
    'max-knuckle': 'Maxipuño',
    'max-phantasm': 'Maxiespectro',
    'max-hailstorm': 'Maxihelada',
    'max-ooze': 'Maxiácido',
    'max-geyser': 'Maxichorro',
    'max-airstream': 'Maxiciclón',
    'max-starfall': 'Maxiestela',
    'max-wyrmwind': 'Maxidraco',
    'max-mindstorm': 'Maxionda',
    'max-rockfall': 'Maxilito',
    'max-quake': 'Maxitemblor',
    'max-darkness': 'Maxisombra',
    'max-overgrowth': 'Maxiflora',
    'max-steelspike': 'Maximetal',
    'clangorous-soul': 'Estruendo Escama',
    'body-press': 'Plancha Corporal',
    decorate: 'Decoración',
    'drum-beating': 'Batería Asalto',
    'snap-trap': 'Cepo',
    'pyro-ball': 'Balón Ígneo',
    'behemoth-blade': 'Tajo Supremo',
    'behemoth-bash': 'Embate Supremo',
    'aura-wheel': 'Rueda Aural',
    'breaking-swipe': 'Vasto Impacto',
    'branch-poke': 'Punzada Rama',
    overdrive: 'Amplificador',
    'apple-acid': 'Ácido Málico',
    'grav-apple': 'Fuerza G',
    'spirit-break': 'Choque Anímico',
    'strange-steam': 'Cautivapor',
    'life-dew': 'Gota Vital',
    obstruct: 'Obstrucción',
    'false-surrender': 'Irreverencia',
    'meteor-assault': 'Asalto Estelar',
    eternabeam: 'Rayo Infinito',
    'steel-beam': 'Metaláser',
    'expanding-force': 'Vasta Fuerza',
    'steel-roller': 'Allanador Férreo',
    'scale-shot': 'Ráfaga Escamas',
    'meteor-beam': 'Rayo Meteórico',
    'shell-side-arm': 'Moluscañón',
    'misty-explosion': 'Bruma Explosiva',
    'grassy-glide': 'Fitoimpulso',
    'rising-voltage': 'Alto Voltaje',
    'terrain-pulse': 'Pulso de Campo',
    'skitter-smack': 'Golpe Rastrero',
    'burning-jealousy': 'Envidia Ardiente',
    'lash-out': 'Desahogo',
    poltergeist: 'Poltergeist',
    'corrosive-gas': 'Gas Corrosivo',
    coaching: 'Motivación',
    'flip-turn': 'Viraje',
    'triple-axel': 'Triple Axel',
    'dual-wingbeat': 'Ala Bis',
    'scorching-sands': 'Arenas Ardientes',
    'jungle-healing': 'Cura Selvática',
    'wicked-blow': 'Golpe Oscuro',
    'surging-strikes': 'Azote Torrencial',
    'thunder-cage': 'Electrojaula',
    'dragon-energy': 'Dracoenergía',
    'freezing-glare': 'Mirada Heladora',
    'fiery-wrath': 'Furia Candente',
    'thunderous-kick': 'Patada Relámpago',
    'glacial-lance': 'Lanza Glacial',
    'astral-barrage': 'Orbes Espectro',
    'eerie-spell': 'Conjuro Funesto',
    'dire-claw': 'Garra Nociva',
    'psyshield-bash': 'Asalto Barrera',
    'power-shift': 'Cambiapoder',
    'stone-axe': 'Hachazo Pétreo',
    'springtide-storm': 'Ciclón Primavera',
    'mystical-power': 'Poder Místico',
    'raging-fury': 'Erupción de Ira',
    'wave-crash': 'Envite Acuático',
    chloroblast: 'Clorofiláser',
    'mountain-gale': 'Viento Carámbano',
    'victory-dance': 'Danza Triunfal',
    'headlong-rush': 'Arremetida',
    'barb-barrage': 'Mil Púas Tóxicas',
    'esper-wing': 'Ala Aural',
    'bitter-malice': 'Rencor Reprimido',
    shelter: 'Retracción',
    'triple-arrows': 'Triple Flecha',
    'infernal-parade': 'Marcha Espectral',
    'ceaseless-edge': 'Tajo Metralla',
    'bleakwind-storm': 'Vendaval Gélido',
    'wildbolt-storm': 'Electormenta',
    'sandsear-storm': 'Simún de Arena',
    'lunar-blessing': 'Plegaria Lunar',
    'take-heart': 'Bálsamo Osado',
    'tera-blast': 'Teraexplosión',
    'silk-trap': 'Telatrampa',
    'axe-kick': 'Patada Hacha',
    'last-respects': 'Homenaje Póstumo',
    'lumina-crash': 'Fotocolisión',
    'order-up': 'Oído Cocina',
    'jet-punch': 'Puño Jet',
    'spicy-extract': 'Extracto Picante',
    'spin-out': 'Quemarrueda',
    'population-bomb': 'Proliferación',
    'ice-spinner': 'Pirueta Helada',
    'glaive-rush': 'Asalto Espadón',
    'revival-blessing': 'Plegaria Vital',
    'salt-cure': 'Salazón',
    'triple-dive': 'Triple Inmersión',
    'mortal-spin': 'Giro Mortífero',
    doodle: 'Decalcomanía',
    'fillet-away': 'Deslome',
    'kowtow-cleave': 'Genufendiente',
    'flower-trick': 'Truco Floral',
    'torch-song': 'Canto Ardiente',
    'aqua-step': 'Danza Acuática',
    'raging-bull': 'Furia Taurina',
    'make-it-rain': 'Fiebre Dorada',
    psyblade: 'Psicohojas',
    'hydro-steam': 'Hidrovapor',
    ruination: 'Calamidad',
    'collision-course': 'Nitrochoque',
    'electro-drift': 'Electroderrape',
    'shed-tail': 'Autotomía',
    'chilly-reception': 'Fría Acogida',
    'tidy-up': 'Limpieza General',
    snowscape: 'Paisaje Nevado',
    pounce: 'Brinco',
    trailblaze: 'Abrecaminos',
    'chilling-water': 'Agua Fría',
    'hyper-drill': 'Hipertaladro',
    'twin-beam': 'Láser Doble',
    'rage-fist': 'Puño Furia',
    'armor-cannon': 'Cañón Armadura',
    'bitter-blade': 'Espada Lamento',
    'double-shock': 'Electropalmas',
    'gigaton-hammer': 'Martillo Colosal',
    comeuppance: 'Resurgimiento',
    'aqua-cutter': 'Tajo Acuático',
    'blazing-torque': 'Pirochoque',
    'wicked-torque': 'Ominochoque',
    'noxious-torque': 'Ponzochoque',
    'combat-torque': 'Pugnachoque',
    'magical-torque': 'Feerichoque',
    'blood-moon': 'Luna Roja',
    'matcha-gotcha': 'Cañón Batidor',
    'syrup-bomb': 'Bomba Caramelo',
    'ivy-cudgel': 'Garrote Liana',
    'electro-shot': 'Electrorrayo',
    'tera-starstorm': 'Teraclúster',
    'fickle-beam': 'Láser Veleidoso',
    'burning-bulwark': 'Llama Protectora',
    thunderclap: 'Relámpago Súbito',
    'mighty-cleave': 'Filo Potente',
    'tachyon-cutter': 'Tajo Taquión',
    'hard-press': 'Prensa Metálica',
    'dragon-cheer': 'Bramido Dragón',
    'alluring-voice': 'Canto Encantador',
    'temper-flare': 'Cólera Ardiente',
    'supercell-slam': 'Plancha Voltaica',
    'psychic-noise': 'Psicorruido',
    'upper-hand': 'Palma Rauda',
    'malignant-chain': 'Cadena Virulenta'
  }

  mapType(type: any): string {
    const name = type?.type?.name ?? type;
    return this.typeMap[name] ?? name;
  }

  mapAbility(ability: any): string {
    const name = ability?.ability?.name ?? ability;
    return this.abilityMap[name] ?? name;
  }

  mapPokemon(p: any): Pokemon {
    return {
      ...p,

      sprite:
        p.sprites?.other?.showdown?.front_default ??
        p.sprites?.other?.home?.front_default ??
        p.sprites?.front_default ??
        '',

      // Tipos SIN traducir
      types: p.types.map((t: any) => ({
        ...t,
        type: {
          name: t.type.name
        }
      })),

      // Habilidades SIN traducir
      abilities: p.abilities.map((a: any) => ({
        ...a,
        ability: {
          name: a.ability.name
        }
      })),

      height: p.height,
      weight: p.weight,

      // Stats SIN traducir
      stats: p.stats.map((s: any) => ({
        ...s,
        stat: {
          name: s.stat.name
        }
      }))
    };
  }

  mapPokemonDetail(vm: any): PokemonDetailVM {
    if (!vm?.pokemon) {
      console.error('VM inválido:', vm);
      throw new Error('pokemon es undefined en mapPokemonDetail');
    }
    return {
      pokemon: this.mapPokemon(vm.pokemon),
      strengths: (vm.strengths ?? []).map((t: string) => this.typeMap[t] ?? t),
      weaknesses: (vm.weaknesses ?? []).map((t: string) => this.typeMap[t] ?? t),
      immunities: (vm.immunities ?? []).map((t: string) => this.typeMap[t] ?? t),
      abilities: (vm.abilities ?? []).map((a: AbilityVM) => ({
        name: this.abilityMap[a.name] ?? a.name,
        description: this.descriptionMap[a.description] ?? a.description
      })),
      description: vm.description,
      evolutionTree: vm.evolutionTree
    };
  }

}